<div class="container-fluid">
    <!--begin::Start Navbar Links-->
    <?php View::partial("adminlte/sub_menus")?>
    <!--end::Start Navbar Links-->

    <!--begin::End Navbar Links-->
    <ul class="navbar-nav ms-auto">

        <!--begin::Notifications Dropdown Menu-->

        <?php View::partial("adminlte/menu_notificaciones")?>

        <!--end::Notifications Dropdown Menu-->

        <!--begin::Fullscreen Toggle-->

        <?php View::partial("adminlte/menu_pantallacompleta")?>

        <!--end::Fullscreen Toggle-->

        <!--begin::User Menu Dropdown-->

        <?php View::partial("adminlte/menu_perfil")?>

        <!--end::User Menu Dropdown-->
    </ul>
    <!--end::End Navbar Links-->
</div>
