

<li class="nav-item dropdown user-menu">

    <!-- aqui va la imafen que paracece  -->
    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <img
            src="/kumbia/libs/adminlte/dist/assets/img/user2-160x160.jpg"
            class="user-image rounded-circle shadow"
            alt="User Image"
        />
        <span class="d-none d-md-inline"><span class="nombre-usuario"></span></span>
    </a>


    <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
        <!--begin::User Image-->
        <li class="user-header text-bg-primary">
            <img
                src="/kumbia/libs/adminlte/dist/assets/img/user2-160x160.jpg"
                class="rounded-circle shadow"
                alt="User Image"
            />
            <p>
            <span class="nombre-usuario"></span>
            </p>
        </li>
        <!--end::User Image-->
        <!--begin::Menu Body-->

        <!--end::Menu Body-->
        <!--begin::Menu Footer-->
        <li class="user-footer">
            <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
            <a href="/kumbia/index/logout" class="btn btn-default btn-flat float-end"
               onclick="localStorage.removeItem('usuario_app');">
                Cerrar sesión
            </a>
        </li>
        <!--end::Menu Footer-->
    </ul>
</li>


