<div class="sidebar-wrapper">
    <nav class="mt-2">
        <!--begin::Sidebar Menu-->
        <ul
            class="nav sidebar-menu flex-column"
            data-lte-toggle="treeview"
            role="navigation"
            aria-label="Main navigation"
            data-accordion="false"
            id="navigation"
        >
            <li class="nav-item menu-open">
                <a href="#" class="nav-link active">
                    <i class="nav-icon bi bi-speedometer"></i>
                    <p>
                        Dashboard
                        <i class="nav-arrow bi bi-chevron-right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                            <a href="/kumbia/" class="nav-link active">
                            <i class="nav-icon bi bi-circle"></i>
                            <p>Inicio</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="<?php echo PUBLIC_PATH ?>graficas/" class="nav-link">
                            <i class="nav-icon bi bi-circle"></i>
                            <p>Graficas</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/kumbia/libs/adminlte/dist/index3.html" class="nav-link">
                            <i class="nav-icon bi bi-circle"></i>
                            <p>historial</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/kumbia/libs/adminlte/dist/index3.html" class="nav-link">
                            <i class="nav-icon bi bi-circle"></i>
                            <p>Reportes</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-header">Login</li>
            <li class="nav-item">
                <a href="/kumbia/libs/adminlte/dist/examples/login-v2.html" class="nav-link">
                    <i class="nav-icon bi bi-circle"></i>
                    <p>Login</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="/kumbia/libs/adminlte/dist/examples/register-v2.html" class="nav-link">
                    <i class="nav-icon bi bi-circle"></i>
                    <p>Register</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="/kumbia/libs/adminlte/dist/examples/lockscreen.html" class="nav-link">
                    <i class="nav-icon bi bi-circle"></i>
                    <p>Lockscreen</p>
                </a>
            </li>

        </ul>

    </nav>
</div>